PCI-1724 [Docker updater] Enable working with multiple repositories
Pix4D/dependabot-core pull request #116
Opened 2021-02-04 10:29 UTC by aliculPix4D

- Docker updater main script can now be used for updating multiple repositories instead of a single one

2021-02-04 10:33 UTC, Pix4D-Janus commented
Your pipeline is set.
Check it here:https://builder.ci.pix4d.com/teams/developers/pipelines/dependabot-PCI-1724-refactor-docker-updater

2021-02-04 10:50 UTC, manuel-pix4d approved these changes
Very hard to read through this ruby code, but it looks good to me. Thanks for taking care of the docker updater !

2021-02-04 11:20 UTC, marco-m-pix4d requested changes
It seems to me that this PR is missing tests for the feature it is adding (the modifications to the tests only adapt to the modified function signature). Can we add some tests?

2021-02-04 14:05 UTC, aliculPix4D commented
> It seems to me that this PR is missing tests for the feature it is adding (the modifications to the tests only adapt to the modified function signature). Can we add some tests?

Any advice on what to actually test here? My understanding: 
- this is the main program
- each important method is already tested
- there is no "new" features here, only reducing the number of input environmental variables
- I have already added assertions to verify that:
1) input is not empty dictonary
```
raise KeyError, "REPOSITORY_DATA should not be empty" if item.keys.empty?
```
2) have the correct keys
```
raise KeyError, "REPOSITORY_DATA should contain 4 non empty keys" unless missing_keys.empty?
```

2021-02-04 14:06 UTC, odormond requested changes

2021-02-04 14:06 UTC, odormond commented on docker/dependabot-main.rb
> +    }]
Why do you redefine `credentials_docker` for each item? The value is always the same.

2021-02-04 14:06 UTC, odormond commented on docker/dependabot-main.rb
> +  raise KeyError, "REPOSITORY_DATA should not be empty" if item.keys.empty?
`REPOSITORY_DATA` is not empty as a matter of fact otherwise you wouldn't have an item to complain about its keys.

So this error message needs fixing but you need also to check before even trying to loop on the parsed yaml that it resulted in a non-empty list in the first place. If `REPOSITORY_DATA` is set to the string `foo`, it will be parsed as it is a valid yaml file containing a singe string value and not a list.

2021-02-09 08:39 UTC, aliculPix4D commented
Closed in favor of: 
1) https://github.com/Pix4D/dependabot-core/pull/118
2) https://github.com/Pix4D/dependabot-core/pull/119

2021-02-09 08:39 UTC, closed without merging

2021-02-09 08:39 UTC, aliculPix4D commented on docker/dependabot-main.rb
> +  raise KeyError, "REPOSITORY_DATA should not be empty" if item.keys.empty?
Comment is addressed in https://github.com/Pix4D/dependabot-core/pull/119

2021-02-09 08:39 UTC, aliculPix4D commented on docker/dependabot-main.rb
> +    }]
Comment is addressed in https://github.com/Pix4D/dependabot-core/pull/119

2021-02-09 08:41 UTC, aliculPix4D commented
> It seems to me that this PR is missing tests for the feature it is adding (the modifications to the tests only adapt to the modified function signature). Can we add some tests?

Please have a look at:
https://github.com/Pix4D/dependabot-core/pull/118
https://github.com/Pix4D/dependabot-core/pull/119